-- ─────────────────────────────────────────────────────────────────────────────
-- Granite — Seed approved users (per-email gating)
-- Run AFTER 00_base_schema.sql and setup_auto_approval.sql.
-- Adds each staff email to auto_approved so registration auto-approves them.
-- Remove a row here (and the person's profile) to revoke access when they leave.
-- Provisional lists supplied 3 Jun 2026 (phillip.mckeown@me.com intentionally omitted).
-- ─────────────────────────────────────────────────────────────────────────────

insert into auto_approved (type, value, note) values
  ('email', 'siobhan.mccartan@crashservices.com', 'CRASH'),
  ('email', 'aisling.orourke@crashservices.com', 'CRASH'),
  ('email', 'amy.heaney@crashservices.com', 'CRASH'),
  ('email', 'anna.johnston@crashservices.com', 'CRASH'),
  ('email', 'brid.quinn@crashservices.com', 'CRASH'),
  ('email', 'brigid.phelan@crashservices.com', 'CRASH'),
  ('email', 'rosanne.boyle@crashservices.com', 'CRASH'),
  ('email', 'niamh.shannon@crashservices.com', 'CRASH'),
  ('email', 'irene.canavan@crashservices.com', 'CRASH'),
  ('email', 'cherith.stanfield@crashservices.com', 'CRASH'),
  ('email', 'mairead.morgan@crashservices.com', 'CRASH'),
  ('email', 'clare.dowdall@crashservices.com', 'CRASH'),
  ('email', 'kathy.mcnally@crashservices.com', 'CRASH'),
  ('email', 'marie.keenan@crashservices.com', 'CRASH'),
  ('email', 'stephen.savage@crashservices.com', 'CRASH'),
  ('email', 'sinead@crashservices.com', 'CRASH'),
  ('email', 'ailis.mckeown@jmksolicitors.com', 'JMK'),
  ('email', 'alex.stephenson@jmksolicitors.com', 'JMK'),
  ('email', 'alyssia.mcanee@jmksolicitors.com', 'JMK'),
  ('email', 'amy.bradford@jmksolicitors.com', 'JMK'),
  ('email', 'amy.goss@jmksolicitors.com', 'JMK'),
  ('email', 'andrew.moore@jmksolicitors.com', 'JMK'),
  ('email', 'aoife.killackey@jmksolicitors.com', 'JMK'),
  ('email', 'ashleen@jmksolicitors.com', 'JMK'),
  ('email', 'brogan.brady@jmksolicitors.com', 'JMK'),
  ('email', 'bronach.mcnally@jmksolicitors.com', 'JMK'),
  ('email', 'caitlin.brown@jmksolicitors.com', 'JMK'),
  ('email', 'carmel@jmksolicitors.com', 'JMK'),
  ('email', 'caroline.cahill@jmksolicitors.com', 'JMK'),
  ('email', 'ciaran.mcardle@jmksolicitors.com', 'JMK'),
  ('email', 'cieran.marshall@jmksolicitors.com', 'JMK'),
  ('email', 'claire.waring@jmksolicitors.com', 'JMK'),
  ('email', 'cliodhna.daykin@jmksolicitors.com', 'JMK'),
  ('email', 'clodagh.upton@jmksolicitors.com', 'JMK'),
  ('email', 'colleen.ward@jmksolicitors.com', 'JMK'),
  ('email', 'danielle.booth@jmksolicitors.com', 'JMK'),
  ('email', 'edel.quigley@jmksolicitors.com', 'JMK'),
  ('email', 'ellie.jennings@jmksolicitors.com', 'JMK'),
  ('email', 'ellie.mcguigan@jmksolicitors.com', 'JMK'),
  ('email', 'erin.mcallister@jmksolicitors.com', 'JMK'),
  ('email', 'gabriele.mikstaite@jmksolicitors.com', 'JMK'),
  ('email', 'gavin.early@jmksolicitors.com', 'JMK'),
  ('email', 'gemma.crane@jmksolicitors.com', 'JMK'),
  ('email', 'georgia.gray@jmksolicitors.com', 'JMK'),
  ('email', 'hannah.mayes@jmksolicitors.com', 'JMK'),
  ('email', 'gerry.casey@jmksolicitors.com', 'JMK'),
  ('email', 'helen.brown@jmksolicitors.com', 'JMK'),
  ('email', 'jemma.hegarty@jmksolicitors.com', 'JMK'),
  ('email', 'jordan.kelly@jmksolicitors.com', 'JMK'),
  ('email', 'karl.ohagan@jmksolicitors.com', 'JMK'),
  ('email', 'kathy@jmksolicitors.com', 'JMK'),
  ('email', 'katie.taggart@jmksolicitors.com', 'JMK'),
  ('email', 'katrina.mclaughlin@jmksolicitors.com', 'JMK'),
  ('email', 'keri.whiteside@jmksolicitors.com', 'JMK'),
  ('email', 'kerrimarie.brophy@jmksolicitors.com', 'JMK'),
  ('email', 'kerry.hughes@jmksolicitors.com', 'JMK'),
  ('email', 'laura.lynn@jmksolicitors.com', 'JMK'),
  ('email', 'lauren.fegan@jmksolicitors.com', 'JMK'),
  ('email', 'lauren.leslie@jmksolicitors.com', 'JMK'),
  ('email', 'leah.mcgee@jmksolicitors.com', 'JMK'),
  ('email', 'lorna.mckeown@jmksolicitors.com', 'JMK'),
  ('email', 'lorraine@jmksolicitors.com', 'JMK'),
  ('email', 'louise@jmksolicitors.com', 'JMK'),
  ('email', 'mairead.hughes@jmksolicitors.com', 'JMK'),
  ('email', 'marieclaire@jmksolicitors.com', 'JMK'),
  ('email', 'maurece@jmksolicitors.com', 'JMK'),
  ('email', 'niall.smyth@jmksolicitors.com', 'JMK'),
  ('email', 'niamh.campbell@jmksolicitors.com', 'JMK'),
  ('email', 'nikhil.kane@jmksolicitors.com', 'JMK'),
  ('email', 'orla.mcgillian@jmksolicitors.com', 'JMK'),
  ('email', 'paige.clements@jmksolicitors.com', 'JMK'),
  ('email', 'paul.obrien@jmksolicitors.com', 'JMK'),
  ('email', 'rebecca.munroe@jmksolicitors.com', 'JMK'),
  ('email', 'rebekah.kennedy@jmksolicitors.com', 'JMK'),
  ('email', 'roisin.morgan@jmksolicitors.com', 'JMK'),
  ('email', 'ryan.ohanlon@jmksolicitors.com', 'JMK'),
  ('email', 'simmone.bell@jmksolicitors.com', 'JMK'),
  ('email', 'sinead.sinclair@jmksolicitors.com', 'JMK'),
  ('email', 'sineadtoal@jmksolicitors.com', 'JMK'),
  ('email', 'sorchamay.davidson@jmksolicitors.com', 'JMK'),
  ('email', 'steven.gilliland@jmksolicitors.com', 'JMK'),
  ('email', 'susanmorrison@jmksolicitors.com', 'JMK'),
  ('email', 'una@jmksolicitors.com', 'JMK'),
  ('email', 'wendy.mcintosh@jmksolicitors.com', 'JMK'),
  ('email', 'will.polland@jmksolicitors.com', 'JMK'),
  ('email', 'jonathan@jmksolicitors.com', 'JMK')
on conflict (lower(value)) do nothing;
